name: CI Pipeline

on:
    push:
        branches:
            - main
            - feature/user-login
    pull_request:
        branches:
            - main    
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            
            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run tests
              run: Pytest    

            


